# Generated by Django 5.0.6 on 2024-06-16 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIUser',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apiuser')),
            ],
        ),
    ]
